# home-manager/utilities/p10k.nix
# Powerlevel10k configuration with Stylix base16 colors
# Uses truecolor hex colors for multiline prompt decorations
{
  config,
  pkgs,
  ...
}: let
  # Access Stylix base16 color scheme
  c = config.lib.stylix.colors;

  # Map Stylix base16 colors to 256-color equivalents for p10k segments
  # p10k's POWERLEVEL9K_*_FOREGROUND/BACKGROUND only accept 256-color numbers
  color256 = {
    # Base16 background colors -> 256-color equivalents
    bg0 = "0";      # base00 - darkest background
    bg1 = "233";    # base01 - slightly lighter
    bg2 = "235";    # base02 - selection background
    bg3 = "238";    # base03 - comments/invisibles
    bg4 = "240";    # base04 - dark foreground
    
    # Base16 foreground colors -> 256-color equivalents
    fg0 = "255";    # base07 - lightest foreground
    fg1 = "253";    # base06 - light foreground
    fg2 = "250";    # base05 - default foreground
    fg3 = "240";    # base04 - dark foreground
    
    # Semantic colors
    red = "196";    # base08 - errors
    orange = "208"; # base09 - warnings/special
    yellow = "220"; # base0A - warnings
    green = "114";  # base0B - success
    cyan = "116";   # base0C - info
    blue = "69";    # base0D - primary
    magenta = "132";# base0E - highlights
    brown = "131";  # base0F - dark red
  };

  # Helper function to create zsh truecolor foreground escape sequence
  fg = hex: "%F{#${hex}}";
  # Helper function to create zsh truecolor background escape sequence
  bg = hex: "%K{#${hex}}";
in {
  # Generate p10k.zsh with Stylix colors
  home.file.".p10k.zsh".text = ''
    # Powerlevel10k configuration
    # Generated by Nix with Stylix base16 colors
    
    # Temporarily disable options
    emulate -L zsh
    setopt typeset_silent extended_glob nomatch no_unset
    
    # If p10k config is already loaded, reload and exit
    (( $#parameter_cache )) && {
      (( $+parameters[p9k_config_opts] )) || {
        typeset -g -a p9k_config_opts
        setopt ''${p9k_config_opts[@]}
        return
      }
    }
    
    # Prompt elements configuration
    typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
      os_icon                 # OS identifier icon
      context                 # user@hostname
      dir                     # current directory
      vcs                     # git status
      prompt_char             # prompt symbol
    )
    
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
      status
      command_execution_time
      background_jobs
      direnv
      asdf
      virtualenv
      anaconda
      pyenv
      goenv
      nodenv
      nvm
      nodeenv
      node_version
      go_version
      rust_version
      dotnet_version
      php_version
      laravel_version
      java_version
      package
      rvm
      fvm
      luaenv
      jenv
      plenv
      perlbrew
      phpenv
      scalaenv
      haskell_stack
      terraform
      terraform_version
      kubecontext
      aws
      aws_eb_env
      azure
      gcloud
      google_app_cred
      toolbox
      public_ip
      vpn_ip
      ip
      proxy
      battery
      wifi
      time
      todo
      timewarrior
      taskwarrior
      per_directory_history
      cpu_arch
    )
    
    # Character set
    typeset -g POWERLEVEL9K_MODE=nerdfont-v3
    typeset -g POWERLEVEL9K_ICON_PADDING=none
    typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=
    
    # Prompt formatting
    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
    
    # Multiline prompt using truecolor hex colors from Stylix
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='${fg "${c.base03}"}╭─'
    typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='${fg "${c.base03}"}├─'
    typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='${fg "${c.base03}"}╰─'
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='${fg "${c.base03}"}─╮'
    typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='${fg "${c.base03}"}─┤'
    typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='${fg "${c.base03}"}─╯'
    
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=' '
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
    typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
    
    if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
      typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=${color256.bg3}
      typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
      typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
    fi
    
    # Separators
    typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5'
    typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7'
    typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
    typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'
    typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
    typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='░▒▓'
    typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='▓▒░'
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
    
    # Segment: os_icon
    typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=${color256.bg3}
    
    # Segment: prompt_char
    typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
    typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true
    
    # Segment: dir
    typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
    typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
    typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
    typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=${color256.fg2}
    typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=${color256.fg0}
    typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
    typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3
    typeset -g POWERLEVEL9K_DIR_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_DIR_FOREGROUND=${color256.fg0}
    typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_BACKGROUND=${color256.blue}
    
    # Segment: vcs
    typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=' '
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
    typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=${color256.green}
    typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=${color256.green}
    typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=${color256.bg3}
    
    # Segment: context
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
    typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
    typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
    typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
    
    # Segment: status
    typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
    typeset -g POWERLEVEL9K_STATUS_OK=true
    typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
    typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_STATUS_ERROR=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
    typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=${color256.red}
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
    typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=${color256.red}
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=${color256.red}
    
    # Segment: command_execution_time
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
    typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PREFIX='took '
    
    # Segment: background_jobs
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=${color256.cyan}
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
    
    # Segment: direnv
    typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=${color256.bg0}
    
    # Segment: asdf
    typeset -g POWERLEVEL9K_ASDF_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_ASDF_BACKGROUND=${color256.bg3}
    
    # Segment: virtualenv
    typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_VIRTUALENV_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_PYTHON_VERSION=false
    typeset -g POWERLEVEL9K_VIRTUALENV_SHOW_WITH_PYENV=false
    typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
    
    # Segment: anaconda
    typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_ANACONDA_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_ANACONDA_CONTENT_EXPANSION=''${''${''${''${CONDA_PROMPT_MODIFIER#\(}% }%\)}:-''${CONDA_PREFIX:t}}
    
    # Segment: pyenv
    typeset -g POWERLEVEL9K_PYENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PYENV_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_PYENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_PYENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_PYENV_SHOW_SYSTEM=true
    typeset -g POWERLEVEL9K_PYENV_CONTENT_EXPANSION=''${P9K_CONTENT}''${''${P9K_CONTENT:#$P9K_PYENV_PYTHON_VERSION(|/*)}:+ $P9K_PYENV_PYTHON_VERSION}
    
    # Segment: goenv
    typeset -g POWERLEVEL9K_GOENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_GOENV_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_GOENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_GOENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_GOENV_SHOW_SYSTEM=true
    
    # Segment: nodenv
    typeset -g POWERLEVEL9K_NODENV_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_NODENV_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_NODENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_NODENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_NODENV_SHOW_SYSTEM=true
    
    # Segment: nvm
    typeset -g POWERLEVEL9K_NVM_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_NVM_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_NVM_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_NVM_SHOW_SYSTEM=true
    
    # Segment: nodeenv
    typeset -g POWERLEVEL9K_NODEENV_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_NODEENV_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_NODEENV_SHOW_NODE_VERSION=false
    typeset -g POWERLEVEL9K_NODEENV_{LEFT,RIGHT}_DELIMITER=
    
    # Segment: node_version
    typeset -g POWERLEVEL9K_NODE_VERSION_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_NODE_VERSION_BACKGROUND=${color256.green}
    typeset -g POWERLEVEL9K_NODE_VERSION_PROJECT_ONLY=true
    
    # Segment: go_version
    typeset -g POWERLEVEL9K_GO_VERSION_FOREGROUND=${color256.fg0}
    typeset -g POWERLEVEL9K_GO_VERSION_BACKGROUND=${color256.green}
    typeset -g POWERLEVEL9K_GO_VERSION_PROJECT_ONLY=true
    
    # Segment: rust_version
    typeset -g POWERLEVEL9K_RUST_VERSION_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_RUST_VERSION_BACKGROUND=${color256.orange}
    typeset -g POWERLEVEL9K_RUST_VERSION_PROJECT_ONLY=true
    
    # Segment: dotnet_version
    typeset -g POWERLEVEL9K_DOTNET_VERSION_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_DOTNET_VERSION_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_DOTNET_VERSION_PROJECT_ONLY=true
    
    # Segment: php_version
    typeset -g POWERLEVEL9K_PHP_VERSION_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PHP_VERSION_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_PHP_VERSION_PROJECT_ONLY=true
    
    # Segment: laravel_version
    typeset -g POWERLEVEL9K_LARAVEL_VERSION_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_LARAVEL_VERSION_BACKGROUND=${color256.bg3}
    
    # Segment: java_version
    typeset -g POWERLEVEL9K_JAVA_VERSION_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_JAVA_VERSION_BACKGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_JAVA_VERSION_PROJECT_ONLY=true
    typeset -g POWERLEVEL9K_JAVA_VERSION_FULL=false
    
    # Segment: package
    typeset -g POWERLEVEL9K_PACKAGE_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PACKAGE_BACKGROUND=${color256.cyan}
    
    # Segment: rvm
    typeset -g POWERLEVEL9K_RVM_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_RVM_BACKGROUND=${color256.bg4}
    typeset -g POWERLEVEL9K_RVM_SHOW_GEMSET=false
    typeset -g POWERLEVEL9K_RVM_SHOW_PREFIX=false
    
    # Segment: fvm
    typeset -g POWERLEVEL9K_FVM_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_FVM_BACKGROUND=${color256.blue}
    
    # Segment: luaenv
    typeset -g POWERLEVEL9K_LUAENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_LUAENV_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_LUAENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_LUAENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_LUAENV_SHOW_SYSTEM=true
    
    # Segment: jenv
    typeset -g POWERLEVEL9K_JENV_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_JENV_BACKGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_JENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_JENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_JENV_SHOW_SYSTEM=true
    
    # Segment: plenv
    typeset -g POWERLEVEL9K_PLENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PLENV_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_PLENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_PLENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_PLENV_SHOW_SYSTEM=true
    
    # Segment: perlbrew
    typeset -g POWERLEVEL9K_PERLBREW_FOREGROUND="67"
    typeset -g POWERLEVEL9K_PERLBREW_PROJECT_ONLY=true
    typeset -g POWERLEVEL9K_PERLBREW_SHOW_PREFIX=false
    
    # Segment: phpenv
    typeset -g POWERLEVEL9K_PHPENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PHPENV_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_PHPENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_PHPENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_PHPENV_SHOW_SYSTEM=true
    
    # Segment: scalaenv
    typeset -g POWERLEVEL9K_SCALAENV_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_SCALAENV_BACKGROUND=${color256.red}
    typeset -g POWERLEVEL9K_SCALAENV_SOURCES=(shell local global)
    typeset -g POWERLEVEL9K_SCALAENV_PROMPT_ALWAYS_SHOW=false
    typeset -g POWERLEVEL9K_SCALAENV_SHOW_SYSTEM=true
    
    # Segment: haskell_stack
    typeset -g POWERLEVEL9K_HASKELL_STACK_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_HASKELL_STACK_BACKGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_HASKELL_STACK_SOURCES=(shell local)
    typeset -g POWERLEVEL9K_HASKELL_STACK_ALWAYS_SHOW=true
    
    # Segment: terraform
    typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
    typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=(
        '*'         OTHER)
    typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=${color256.bg0}
    
    # Segment: terraform_version
    typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_TERRAFORM_VERSION_SHOW_ON_COMMAND='terraform|tf'
    
    # Segment: kubecontext
    typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
    typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
        '*'       DEFAULT)
    typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='''${P9K_KUBECONTEXT_CLOUD_CLUSTER:-''${P9K_KUBECONTEXT_NAME}}'
    POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='''${''${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'
    typeset -g POWERLEVEL9K_KUBECONTEXT_PREFIX='at '
    
    # Segment: aws
    typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|cdk|terraform|pulumi|terragrunt'
    typeset -g POWERLEVEL9K_AWS_CLASSES=(
        '*'       DEFAULT)
    typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=${color256.red}
    typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='''${P9K_AWS_PROFILE//\%/%%}''${P9K_AWS_REGION:+ ''${P9K_AWS_REGION//\%/%%}}
    
    # Segment: aws_eb_env
    typeset -g POWERLEVEL9K_AWS_EB_ENV_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_AWS_EB_ENV_BACKGROUND=${color256.bg0}
    
    # Segment: azure
    typeset -g POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi|terragrunt'
    typeset -g POWERLEVEL9K_AZURE_CLASSES=(
        '*'         OTHER)
    typeset -g POWERLEVEL9K_AZURE_OTHER_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_AZURE_OTHER_BACKGROUND=${color256.blue}
    
    # Segment: gcloud
    typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
    typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='''${P9K_GCLOUD_PROJECT_ID//\%/%%}'
    typeset -g POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='''${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
    typeset -g POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60
    
    # Segment: google_app_cred
    typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi|terragrunt'
    typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=(
        '*'             DEFAULT)
    typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='''${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}
    
    # Segment: toolbox
    typeset -g POWERLEVEL9K_TOOLBOX_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_TOOLBOX_BACKGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_TOOLBOX_CONTENT_EXPANSION='''${P9K_TOOLBOX_NAME:#fedora-toolbox-*}'
    typeset -g POWERLEVEL9K_TOOLBOX_PREFIX='in '
    
    # Segment: public_ip
    typeset -g POWERLEVEL9K_PUBLIC_IP_FOREGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_PUBLIC_IP_BACKGROUND=${color256.bg0}
    
    # Segment: vpn_ip
    typeset -g POWERLEVEL9K_VPN_IP_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_VPN_IP_BACKGROUND=${color256.cyan}
    typeset -g POWERLEVEL9K_VPN_IP_CONTENT_EXPANSION=
    typeset -g POWERLEVEL9K_VPN_IP_INTERFACE='(gpd|wg|(.*tun)|tailscale)[0-9]*|(zt.*)'
    typeset -g POWERLEVEL9K_VPN_IP_SHOW_ALL=false
    
    # Segment: ip
    typeset -g POWERLEVEL9K_IP_BACKGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_IP_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_IP_CONTENT_EXPANSION='''${P9K_IP_RX_RATE:+⇣$P9K_IP_RX_RATE }''${P9K_IP_TX_RATE:+⇡$P9K_IP_TX_RATE }$P9K_IP_IP'
    typeset -g POWERLEVEL9K_IP_INTERFACE='[ew].*'
    
    # Segment: proxy
    typeset -g POWERLEVEL9K_PROXY_FOREGROUND=${color256.blue}
    typeset -g POWERLEVEL9K_PROXY_BACKGROUND=${color256.bg0}
    
    # Segment: battery
    typeset -g POWERLEVEL9K_BATTERY_LOW_THRESHOLD=20
    typeset -g POWERLEVEL9K_BATTERY_LOW_FOREGROUND=${color256.red}
    typeset -g POWERLEVEL9K_BATTERY_{CHARGING,CHARGED}_FOREGROUND=${color256.green}
    typeset -g POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_BATTERY_STAGES='\UF008E\UF007A\UF007B\UF007C\UF007D\UF007E\UF007F\UF0080\UF0081\UF0082\UF0079'
    typeset -g POWERLEVEL9K_BATTERY_VERBOSE=false
    typeset -g POWERLEVEL9K_BATTERY_BACKGROUND=0
    
    # Segment: wifi
    typeset -g POWERLEVEL9K_WIFI_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_WIFI_BACKGROUND=${color256.blue}
    
    # Segment: time
    typeset -g POWERLEVEL9K_TIME_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_TIME_BACKGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
    typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
    typeset -g POWERLEVEL9K_TIME_PREFIX='at '
    
    # Segment: todo
    typeset -g POWERLEVEL9K_TODO_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_TODO_BACKGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_TOTAL=true
    typeset -g POWERLEVEL9K_TODO_HIDE_ZERO_FILTERED=false
    
    # Segment: timewarrior
    typeset -g POWERLEVEL9K_TIMEWARRIOR_FOREGROUND=${color256.fg0}
    typeset -g POWERLEVEL9K_TIMEWARRIOR_BACKGROUND=${color256.bg3}
    typeset -g POWERLEVEL9K_TIMEWARRIOR_CONTENT_EXPANSION='''${P9K_CONTENT:0:24}''${''${P9K_CONTENT:24}:+…}
    
    # Segment: taskwarrior
    typeset -g POWERLEVEL9K_TASKWARRIOR_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_TASKWARRIOR_BACKGROUND=${color256.cyan}
    
    # Segment: per_directory_history
    typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_LOCAL_BACKGROUND=${color256.magenta}
    typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_PER_DIRECTORY_HISTORY_GLOBAL_BACKGROUND=${color256.yellow}
    
    # Segment: cpu_arch
    typeset -g POWERLEVEL9K_CPU_ARCH_FOREGROUND=${color256.bg0}
    typeset -g POWERLEVEL9K_CPU_ARCH_BACKGROUND=${color256.yellow}
    
    # User-defined prompt segments
    function prompt_example() {
      p10k segment -b 1 -f 3 -i '⭐' -t 'hello, %n'
    }
    
    function instant_prompt_example() {
      prompt_example
    }
    
    typeset -g POWERLEVEL9K_EXAMPLE_FOREGROUND=${color256.yellow}
    typeset -g POWERLEVEL9K_EXAMPLE_BACKGROUND=${color256.red}
    
    # Transient prompt
    typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
    
    # Instant prompt
    typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
    
    # Hot reload
    typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
    
    # Reload configuration
    (( ! $+functions[p10k] )) || p10k reload
    
    # Tell p10k which file it should overwrite
    typeset -g POWERLEVEL9K_CONFIG_FILE=''${''${(%):-%x}:a}
    
    (( ''${#p10k_config_opts} )) && setopt ''${p10k_config_opts[@]}
    'builtin' 'unset' 'p10k_config_opts'
  '';
}
